### PR TITLE
Putting all data manipulations into global.R & changing plot 

### PR DESCRIPTION
**Pull request by kmenciso**
Changing widths & heights to be more pleasing.

### CODE REVIEW

**Comment by kmenciso** [comment]
Also what checkbox inputs do you want? I know you said lakes but I realize I don't know what that means. 

Ideally if there is a column in the data that has that info, then I could jut use a unique() to get it

**Comment by Monsauce** [comment]
Two checkbox inputs please. One where users can select "natural" or "man made" the data for this can be found in the LAKE_ORIGIN column. The second where users can select "shallow" or "deep" lakes, where shallow is >= 4 and deep is <= 4 using the DEPTHMAX column.

**Comment by kmenciso** [comment]
OK so what's 4? Like do you want to classify lakes <= 4 as shallow and > as deep or shallow < 4 and deep >=4

**Comment by Monsauce** [comment]
yeah except I talked to Amanda and she said to change it to 5. So greater than or equal to 5 m it is a deep lake, less than 5 is a shallow lake. 

-Mon

**Pull request merged**
